version: '3'

services:
  app:
    image: registry.digitalocean.com/main/aic-api
    ports:
      - "4000:4000"
    env_file:
      - .env
    entrypoint: [ "/bin/sh","-c" ]
    command:
      - |
        node migrations/index.js up
        node src/index.js

  redis:
    image: "redis:latest"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:6
    command: mongod --storageEngine=wiredTiger --replSet rs0
    volumes:
      - mongo_data:/data/db

  mongo-init-replica:
    image: mongo:4.4
    depends_on:
      - mongo
    command: bash -c "sleep 10 && mongo --host mongo --eval 'rs.initiate()'"

volumes:
  redis_data:
  mongo_data:

networks:
  default:
    external:
      name: ${NETWORK:-proxy}
