version: '3'

services:
  app:
    image: registry.digitalocean.com/main/aic-api
    ports:
      - "4000:4000"
    env_file:
      - .env
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        node migrations/index.js up
        node src/index.js


networks:
  default:
    external:
      name: ${NETWORK:-proxy}
