name: Nuxt

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_REGISTRY_DOMAIN: registry.digitalocean.com
  USERNAME: root
  HOST: api.aic.preciselab.io

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag registry.digitalocean.com/main/aic-api
      - name: Login to registry
        run: docker login -u ${{ secrets.DOCKER_TOKEN }} -p ${{ secrets.DOCKER_TOKEN }} ${{ env.DOCKER_REGISTRY_DOMAIN }}
      - name: Build the Docker image
        run: docker push registry.digitalocean.com/main/aic-api

  reload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: prepare env
        run: |
          ENV=$(cat << EOF
          VIRTUAL_HOST=api.aic.preciselab.io
          LETSENCRYPT_HOST=api.aic.preciselab.io
          VIRTUAL_PORT=3000
          EOF
          )
          echo "$ENV" > .env
      - name: read env
        run: cat .env
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [local]
            127.0.0.1 env=prod
            
            [api]
            api.aic.preciselab.io ansible_user=root dir=api
    needs: image
